### ISSUE TITLE
About why Rust is slower

### ISSUE THREAD

**Issue by JRF63** [KoBruhh/RVC_Bench#1]
You're using bounds-checked indexing. Use `get_unchecked` or `get_unchecked_mut` instead of `arr[index as usize]` if you want to extract the maximum performance out of Rust.

Saw your comment on Discord.

**Comment by orhnk** [comment]
thanks that sped up rust a bit but V is faster. I guess the compiler team is doing good job

**Comment by JRF63** [comment]
I was looking at my GitHub activity and saw this issue I made.

Can I mention that [those](https://github.com/UTFeight/RVC_Bench/blob/f0cc503e9ff7832f212595afebc3fef9dda9fc09/Rust/src/main.rs#L44) `swap`s are also [bounds checked](https://doc.rust-lang.org/std/primitive.slice.html#method.swap)? You might want to check out the [`swap_unchecked`](https://doc.rust-lang.org/std/primitive.slice.html#method.swap_unchecked) available in nightly. Or `std::mem::swap`, or manually swap them with unchecked indexing.

Sorry, I just saw the code and couldn't help myself from pointing that out. Aight, Imma crawl back to the hole I came from.
